.TH "TRACKTAG" 1 "April 2011" "" "Audio File Tagger"
.SH NAME
tracktag \- update audio file metadata
.SH SYNOPSIS
tracktag [OPTIONS] <track 1> [track 2] ...
.SH DESCRIPTION
.PP
tracktag takes new metadata values and a list of audio files and updates those files with the new values.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show a list of options and exit
.TP
\fB\-V\fR, \fB\-\-verbose\fR=\fIVERBOSITY\fR
The level of output to display. Choose between 'normal', 'quiet' and 'debug.
.TP
\fB\-r\fR, \fB\-\-replace\fR
this options erases all existing metadata and replaces it with any specified values
.TP
\fB\-x\fR, \fB\-\-xmcd\fR=\fIFILENAME\fR
A MusicBrainz XML file or FreeDB XMCD file to use for track metadata. XML and XMCD files can be obtained from the track2xmcd(1), cd2xmcd(1), dvda2xmcd(1), and editxmcd(1) programs.
.TP
\fB\-\-cue\fR=\fIFILENAME\fR
If given along with multiple audio tracks, this file's ISRC metadata will be added to those tracks; if given with a single CD image track, this file will be embedded in that image. Note that only FLAC and WavPack currently support embedded cuesheets and not all CDs contain ISRC metadata.
.TP
\fB\-\-replay\-gain\fR
add ReplayGain metadata to tracks
.SH TEXT OPTIONS
.TP
\fB\-\-name\fR=\fINAME\fR
the name of the track
.TP
\fB\-\-artist\fR=\fINAME\fR
the track's artist
.TP
\fB\-\-performer\fR=\fINAME\fR
the track's performer
.TP
\fB\-\-composer\fR=\fINAME\fR
the track's composer
.TP
\fB\-\-conductor\fR=\fINAME\fR
the track's conductor
.TP
\fB\-\-album\fR=\fINAME\fR
the track's album name
.TP
\fB\-\-catalog\fR=\fINUMBER\fR
the album's catalog number, typically indicated on its case
.TP
\fB\-\-number\fR=\fINUMBER\fR
the track's number on the disc
.TP
\fB\-\-track\-total\fR=\fINUMBER\fR
the total number of tracks on the disc
.TP
\fB\-\-album\-number\fR=\fINUMBER\fR
the album's number, if it is one in a series of albums; for example, a 3 CD set might have an album number of 1, 2 or 3
.TP
\fB\-\-album\-total\fR=\fINUMBER\fR
the total number of albums in the set
.TP
\fB\-\-ISRC\fR=\fIISRC\fR
the track's ISRC
.TP
\fB\-\-publisher\fR=\fINAME\fR
the album's publisher
.TP
\fB\-\-media\-type\fR=\fIMEDIA\fR
the album's media type, such as "CD", "vinyl", etc.
.TP
\fB\-\-year\fR=\fIYEAR\fR
the album's release year
.TP
\fB\-\-date\fR=\fIDATE\fR
the track's original recording date
.TP
\fB\-\-copyright\fR=\fICOPYRIGHT\fR
the album's copyright information
.TP
\fB\-\-comment\fR=\fITEXT\fR
comment text
.TP
\fB\-\-comment\-file\fR=\fIFILENAME\fR
a file containing comment text, for particularly long comments
.SH IMAGE OPTIONS
.TP
\fB\-\-remove\-images\fR
remove existing images; if new images are added, existing images will be removed beforehand
.TP
\fB\-\-front\-cover\fR=\fIFILENAME\fR
an image file of the album's front cover
.TP
\fB\-\-back\-cover\fR=\fIFILENAME\fR
an image file of the album's back cover
.TP
\fB\-\-leaflet\fR=\fIFILENAME\fR
an image file of one of the album's leaflet pages
.TP
\fB\-\-media\fR=\fIFILENAME\fR
an image file of the album's media
.TP
\fB\-\-other\-image\fR=\fIFILENAME\fR
an image file related to the album
.TP
\fB\-\-thumbnail\fR
convert images to smaller thumbnails before adding
.SH REMOVAL OPTIONS
.TP
\fB\-\-remove\-name\fR
.TP
\fB\-\-remove\-artist\fR
.TP
\fB\-\-remove\-performer\fR
.TP
\fB\-\-remove\-composer\fR
.TP
\fB\-\-remove\-conductor\fR
.TP
\fB\-\-remove\-album\fR
.TP
\fB\-\-remove\-catalog\fR
.TP
\fB\-\-remove\-number\fR
.TP
\fB\-\-remove\-track\-total\fR
.TP
\fB\-\-remove\-album\-number\fR
.TP
\fB\-\-remove\-album\-total\fR
.TP
\fB\-\-remove\-ISRC\fR
.TP
\fB\-\-remove\-publisher\fR
.TP
\fB\-\-remove\-media\-type\fR
.TP
\fB\-\-remove\-year\fR
.TP
\fB\-\-remove\-date\fR
.TP
\fB\-\-remove\-copyright\fR
.TP
\fB\-\-remove\-comment\fR
.SH EXAMPLES
.LP
Update track.flac to be track number 5 and have a track name of "Test Track".
.IP
tracktag "--name=Test Track" --number=5 track.flac

.LP
Add several JPEG images to track.flac
.IP
tracktag --front-cover=front.jpg --back-cover=back.jpg --leaflet=page1.jpg --leaflet=page2.jpg --leaflet=page3.jpg track.flac

.LP
Add ISRC metadata from the disc in /dev/cdrom to all MP3 files in the current directory
.IP
cdrdao read-toc --device /dev/cdrom album.toc

.IP
tracktag --cue=album.toc *.mp3

.SH SEE ALSO
.BR audiotools-config (1),
.BR audiotools.cfg (5),
.BR cd2track (1),
.BR cd2xmcd (1),
.BR cdinfo (1),
.BR cdplay (1),
.BR coverdump (1),
.BR coverview (1),
.BR dvda2track (1),
.BR dvda2xmcd (1),
.BR dvdainfo (1),
.BR editxmcd (1),
.BR track2cd (1),
.BR track2track (1),
.BR track2xmcd (1),
.BR trackcat (1),
.BR trackcmp (1),
.BR trackinfo (1),
.BR tracklength (1),
.BR tracklint (1),
.BR trackplay (1),
.BR trackrename (1),
.BR tracksplit (1),
.BR trackverify (1)
.SH AUTHOR
Brian Langenberger
